home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('homepage', views.loggedInView, name='login'),
    path('logout', views.logout, name='login'),
]

level/urls.py
from django.urls import path
from .views import *

app_name = 'level'
urlpatterns = [
    path('', read_level, name='read_level'),
    path('create', create_level, name='create_level'),
    path('<level>/update', update_level, name='update_level'),
    path('<level>/delete', delete_level, name='delete_level')
]

pekerjaan/urls.py
from django.urls import path

from .views import *

app_name = 'pekerjaan'

urlpatterns = [
    path('', index, name='index'),
    path('create',create_pekerjaan,name='create_pekerjaan'),
    path('bekerja',list_bekerja,name="read_bekerja"),
    path('bekerja/create',create_bekerja,name="create_bekerja"),
    path('<str:nama>/update',update_pekerjaan,name="update_pekerjaan"),
    path('<str:nama>/delete',delete_pekerjaan,name='delete_pekerjaan'),
    
]

thecims/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('level/', include('level.urls')),
    path('warna-kulit/', include('warna_kulit.urls')),
    path('koleksi/', include('koleksi.urls')),
    path('tokoh/',include('tokoh.urls')),
    path('use_barang/',include('use_barang.urls')),
    path('pekerjaan/',include('pekerjaan.urls')),
    path('misi-utama/', include('misi_utama.urls')),
    path('menjalankan-misi-utama/', include('menjalankan_misi_utama.urls')),
    path('makanan/', include('makanan.urls')),
    path('makan/', include('makan.urls')),
    path('menggunakan-apparel/', include('menggunakan_apparel.urls')),
    path('registrasi/', include('registrasi.urls')),
]

tokoh/urls.py
from django.urls import path

from .views import *

app_name = 'tokoh'

urlpatterns = [
    path('', index, name='index'),
    path('create',buat_tokoh,name='buat_tokoh'),
    path('detail/<str:name>/<str:nama>',detail_tokoh,name='detail_tokoh'),
    path('detail/<str:name>/<str:nama>/update',update_tokoh,name='update_tokoh'),

]

use_barang/urls.py
from django.urls import path

from .views import *

app_name = 'use_barang'

urlpatterns = [
    path('', index, name='index'),
    path('create',create_menggunakan_barang,name="create_use_barang")
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=50)
    password = forms.CharField(label='Password', max_length=50)

home/views.py
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render
from django.db import connection
from collections import namedtuple
from .forms import *

# Create your views here.

# Function to return every row of data from query
def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def index(request):
    cursor = connection.cursor()
    result = []
    try:
        cursor.execute("SET SEARCH_PATH TO THECIMS")
        cursor.execute("SELECT EMAIL FROM PEMAIN")
        result = namedtuplefetchall(cursor)
    except Exception as e:
        print(e)
    finally:
        cursor.close()

    return render(request, 'home/index.html', {'result': result})

def login(request):

    result = []

    # Define login form
    MyLoginForm = LoginForm(request.POST)

    # Form submission
    if (MyLoginForm.is_valid() and request.method == 'POST'):
        # Get data from form
        username = MyLoginForm.cleaned_data['username']
        password = MyLoginForm.cleaned_data['password']

        # Run SQL QUERY
        try:
            cursor = connection.cursor()
            cursor.execute("SET SEARCH_PATH TO THECIMS")
            cursor.execute("SELECT * FROM \
                           (SELECT * FROM PEMAIN UNION SELECT username, Null as email, password, Null as no_hp, Null as koin FROM ADMIN) AS P \
                           WHERE username ='" + username + "' AND PASSWORD = '" + password + "'")
            result = cursor.fetchone()
            print(result[1])
            if result[1] == None:
                role = "Admin"
            else:
                role = "Pemain"

            if(result == None): 
                return HttpResponseNotFound("The user does not exist")

            # Redirect the cursor towards public so it can access Django basic features
            cursor.execute("SET SEARCH_PATH TO public")
            request.session['username'] = [username, password, role, result]

        except Exception as e:
            print(e)

        finally:
            # Don't forget to close
            cursor.close()

        return HttpResponseRedirect('/homepage')

    else:
        MyLoginForm = LoginForm()

    return render(request, 'home/login.html', {'form' : MyLoginForm})

# Function to test logged in result
def loggedInView(request):
    if request.session.has_key('username'):
        cursor = connection.cursor()
        result = []
        try:
            cursor.execute("SET SEARCH_PATH TO THECIMS")
            cursor.execute("SELECT * FROM \
                           (SELECT * FROM PEMAIN UNION SELECT username, Null as email, password, Null as no_hp, Null as koin FROM ADMIN) AS P \
                           WHERE USERNAME = '"+ request.session['username'][0] +"'")
            result = namedtuplefetchall(cursor)
            role = request.session['username'][2]
            print(role)
        except Exception as e:
            print(e)
        finally:
            cursor.close()
        
        if role == "Admin":
            return render(request, 'home/home_admin.html', {"result" : result, "role" : role})
        else:
            return render(request, 'home/home_pemain.html', {"result" : result, "role" : role})
    else:
        return HttpResponseRedirect('/login')
    
# Function to log out the user
def logout(request):
   try:
        del request.session['username']
   except:
        pass
   return HttpResponseRedirect('/login')

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block nav %}
    {% if request.session.username.2 == "Admin" %}
      {% include 'navbar_admin.html' %}
    {% else %}
      {% include 'navbar_pemain.html' %}
    {% endif %}
  {% endblock nav %}
  {% block content %}
  {% endblock content %}
</body>

</html>

home/templates/navbar_admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
  </head>

  <body>
    <header style="z-index: 3">
      <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a href="/homepage" class="navbar-brand">TheCimsD03</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Tokoh
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'tokoh:index' %}">List Tokoh</a></li>
                  <li>
                    <a class="dropdown-item" href="{% url 'warna_kulit:create_warna_kulit' %}">Buat Warna Kulit</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'warna_kulit:read_warna_kulit' %}">List Warna Kulit</a>
                  </li>
                  <li><a class="dropdown-item" href="{% url 'level:create_level' %}">Buat Level</a></li>
                  <li><a class="dropdown-item" href="{% url 'level:read_level' %}">List Level</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Pekerjaan
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'pekerjaan:create_pekerjaan' %}">Buat Pekerjaan</a></li>
                  <li><a class="dropdown-item" href="{% url 'pekerjaan:index' %}">List Pekerjaan</a></li>
                  <li><a class="dropdown-item" href="{% url 'pekerjaan:read_bekerja' %}">List Bekerja</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Misi
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="/misi-utama/create">Buat Misi Utama</a></li>
                  <li><a class="dropdown-item" href="/misi-utama/">List Misi Utama</a></li>

                  <li>
                    <a class="dropdown-item" href="/menjalankan-misi-utama/"
                      >List Menjalankan Misi Utama</a
                    >
                  </li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Makan
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="/makanan/create">Buat Makanan</a></li>
                  <li><a class="dropdown-item" href="/makanan/">List Makanan</a></li>

                  <li><a class="dropdown-item" href="/makan/">List Makan</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Koleksi
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li>
                    <a class="dropdown-item" href="koleksi/add">Buat Buat Koleksi</a>
                  </li>
                  <li><a class="dropdown-item" href="koleksi">List Koleksi</a></li>
                  <li>
                    <a class="dropdown-item" href="koleksi/kategori-apparel/add">Buat Kategori Apparel</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="koleksi/kategori-apparel">List Kategori Apparel</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="koleksi/koleksi-tokoh">List Koleksi Tokoh</a>
                  </li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Penggunaan
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li>
                    <a class="dropdown-item" href="{% url 'menggunakan_apparel:read_menggunakan_apparel' %}"
                      >List Menggunakan Apparel</a
                    >
                  </li>

                  <li>
                    <a class="dropdown-item" href="#">List Koleksi Tokoh</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'use_barang:index' %}"
                      >List Menggunakan Barang</a
                    >
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link text-danger" href="/logout">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

home/templates/navbar_pemain.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
  </head>

  <body>
    <header style="z-index: 3">
      <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a href="/homepage" class="navbar-brand">TheCimsD03</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Tokoh
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'tokoh:buat_tokoh' %}">Buat Tokoh</a></li>
                  <li><a class="dropdown-item" href="{% url 'tokoh:index' %}">List Tokoh</a></li>
                  <li>
                    <a class="dropdown-item" href="{% url 'warna_kulit:read_warna_kulit' %}">List Warna Kulit</a>
                  </li>

                  <li><a class="dropdown-item" href="{% url 'level:read_level' %}">List Level</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Pekerjaan
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'pekerjaan:index' %}">List Pekerjaan</a></li>
                  <li><a class="dropdown-item" href="{% url 'pekerjaan:create_bekerja' %}">Buat Bekerja</a></li>
                  <li><a class="dropdown-item" href="{% url 'pekerjaan:read_bekerja' %}">List Bekerja</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Misi
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="/misi-utama/">List Misi Utama</a></li>

                  <li>
                    <a class="dropdown-item" href="/menjalankan-misi-utama/create"
                      >Buat Menjalankan Misi Utama</a
                    >
                  </li>
                  <li>
                    <a class="dropdown-item" href="/menjalankan-misi-utama/"
                      >List Menjalankan Misi Utama</a
                    >
                  </li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Makan
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="/makanan/">List Makanan</a></li>

                  <li><a class="dropdown-item" href="/makan/create">Buat Makan</a></li>
                  <li><a class="dropdown-item" href="/makan/">List Makan</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Koleksi
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="koleksi">List Koleksi</a></li>

                  <li>
                    <a class="dropdown-item" href="koleksi/kategori-apparel">List Kategori Apparel</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="#">Buat Koleksi Tokoh</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="koleksi/koleksi-tokoh">List Koleksi Tokoh</a>
                  </li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Penggunaan
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li>
                    <a class="dropdown-item" href="{% url 'menggunakan_apparel:create_menggunakan_apparel_1' %}"
                      >Buat Menggunakan Apparel</a
                    >
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'menggunakan_apparel:read_menggunakan_apparel' %}"
                      >List Menggunakan Apparel</a
                    >
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'use_barang:create_use_barang' %}"
                      >Buat Menggunakan Barang</a
                    >
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'use_barang:index' %}"
                      >List Menggunakan Barang</a
                    >
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link text-danger" href="/logout">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
      crossorigin="anonymous"
    ></script>
  </body>
</html>