home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('homepage', views.loggedInView, name='login'),
    path('logout', views.logout, name='login'),
]

level/urls.py
from django.urls import path
from .views import *

app_name = 'level'
urlpatterns = [
    path('', read_level, name='read_level'),
    path('create', create_level, name='create_level'),
    path('<level>/update', update_level, name='update_level'),
    path('<level>/delete', delete_level, name='delete_level')
]

thecims/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('level/', include('level.urls')),
    path('warna-kulit/', include('warna_kulit.urls')),
    path('koleksi/', include('koleksi.urls')),
    path('tokoh/',include('tokoh.urls')),
    path('use_barang/',include('use_barang.urls')),
    path('pekerjaan/',include('pekerjaan.urls')),
    path('misi-utama/', include('misi_utama.urls')),
    path('menjalankan-misi-utama/', include('menjalankan_misi_utama.urls')),
    path('makanan/', include('makanan.urls')),
    path('makan/', include('makan.urls')),
    path('menggunakan-apparel/', include('menggunakan_apparel.urls')),
    path('registrasi/', include('registrasi.urls')),
]

level/models.py
from django.db import models

# Create your models here.

level/forms.py
from django import forms

class CreateLevelForm(forms.Form):
    level = forms.IntegerField(label='Level', widget=forms.NumberInput(attrs={'id': 'level', 'placeholder': 'level'}))
    xp = forms.IntegerField(label='XP', widget=forms.NumberInput(attrs={'id': 'xp', 'placeholder': 'xp'}))

class UpdateLevelForm(forms.Form):
    level = forms.IntegerField(label='Level', widget=forms.NumberInput(attrs={'id': 'level', 'placeholder': 'level', 'readonly': True}))
    xp = forms.IntegerField(label='XP', widget=forms.NumberInput(attrs={'id': 'xp', 'placeholder': 'xp'}))

level/views.py
from urllib import response
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.db import connection
from django.shortcuts import redirect
from .forms import *

# role: Admin & Pemain
def read_level(request):
    response = {}
    if request.session.has_key('username'):
        with connection.cursor() as cursor:
            cursor.execute("SET SEARCH_PATH TO THECIMS")
            cursor.execute("SELECT * FROM LEVEL")
            response['daftar_level'] = cursor.fetchall()
            cursor.execute("SELECT * FROM LEVEL L WHERE L.level NOT IN (SELECT T.level FROM TOKOH T)")
            response['daftar_level_deletable'] = cursor.fetchall()
            response['role'] = request.session['username'][2]
        return render(request, 'read_level.html', response)
    return redirect('/login')

# role: Admin
def create_level(request):
    response = {}
    if request.session.has_key('username'):
        if request.session['username'][2] == "Admin":
            if (request.method == "POST"):
                form = CreateLevelForm(request.POST)
                if form.is_valid():
                    level = request.POST['level']
                    xp = request.POST['xp']
                    if check_level_availability(level):
                        with connection.cursor() as cursor:
                            cursor.execute("SET SEARCH_PATH TO THECIMS")
                            cursor.execute("INSERT INTO LEVEL VALUES(%s, %s)", [level, xp])
                        return redirect('/level')
                    else:
                        form.add_error('level', "Level ini sudah tercatat")
                        response["level_form"] = form
                        return render(request, "create_level.html", response)
            form = CreateLevelForm()
            response["level_form"] = form
            return render(request, "create_level.html", response)
    return redirect('/login')

# role: Admin
def update_level(request, level):
    data = {}
    response = {}
    if request.session.has_key('username'):
        if request.session['username'][2] == "Admin":
            if (request.method == "POST"):
                form = UpdateLevelForm(request.POST)
                if form.is_valid():
                    xp = request.POST['xp']
                    with connection.cursor() as cursor:
                        cursor.execute("SET SEARCH_PATH TO THECIMS")
                        cursor.execute("UPDATE LEVEL SET xp = %s WHERE level = %s", [xp, level])
                        return redirect('/level')

            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO THECIMS")
                cursor.execute("SELECT * FROM LEVEL WHERE level = %s", [level])
                level_data = cursor.fetchone()

            data['level'] = level_data[0]
            data['xp'] = level_data[1]
            form = UpdateLevelForm(data)
            response['level_form'] = form
            response['level'] = level

            return render(request, 'update_level.html', response)
    return redirect('/login')

# role: Admin
def delete_level(request, level):
    with connection.cursor() as cursor:
        cursor.execute("SET SEARCH_PATH TO THECIMS")
        cursor.execute("DELETE FROM LEVEL WHERE level = %s", [level])
    return redirect('/level')

def check_level_availability(level):
    result = True
    with connection.cursor() as cursor:
        cursor.execute("SET SEARCH_PATH TO THECIMS")
        cursor.execute("SELECT * FROM LEVEL WHERE level = %s", [level])
        level_row = cursor.fetchone()
        if level_row != None:
            result = False
    return result

level/templates/create_level.html
{% include "navbar_admin.html" %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Create Level</title>
  </head>
  <body>
      <form action="{% url 'level:create_level' %}" method="POST">
        {% csrf_token %}
        <h1>Form Buat Level</h1>
        <br>
        {{ level_form.as_p }}
        <br>
        <button type="submit" value="Submit">Simpan</button>
      </form>
  </body>
</html>

level/templates/read_level.html
{% if role == "Admin" %}
{% include "navbar_admin.html" %}
{% endif %}
{% if role == "Pemain" %}
{% include "navbar_pemain.html" %}
{% endif %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>List Level</title>
    <style>
        table, th, td {
          border: 1px solid black;
          border-collapse: collapse;
        }
    </style>
  </head>
  <body>
      <h1>List Level</h1>
      <br>
      <table>
          <thead>
              <tr>
                  <th>No.</th>
                  <th>Level</th>
                  <th>XP</th>
                  {% if role == "Admin" %}
                  <th>Action</th>
                  {% endif %}
              </tr>
          </thead>
          <tbody>
              {% for level in daftar_level %}
              <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ level.0 }}</td>
                  <td>{{ level.1 }}</td>
                  {% if role == "Admin" %}
                  <td><a href="{{ level.0 }}/update">Update<br>
                  {% if level in daftar_level_deletable  %}
                  <a href="{{ level.0 }}/delete">Delete</td>
                  {% endif %}
                  {% endif %}
              </tr>
              {% endfor %}
          </tbody>
      </table>
  </body>
</html>

level/templates/update_level.html
{% include "navbar_admin.html" %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Update Level</title>
  </head>
  <body>
      <form action="{% url 'level:update_level' level=level %}" method="POST">
        {% csrf_token %}
        <h1>Form Ubah Level</h1>
        <br>
        {{ level_form.as_p }}
        <br>
        <button type="submit" value="Submit">Simpan</button>
      </form>
  </body>
</html>