home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('homepage', views.loggedInView, name='login'),
    path('logout', views.logout, name='login'),
]

pekerjaan/urls.py
from django.urls import path

from .views import *

app_name = 'pekerjaan'

urlpatterns = [
    path('', index, name='index'),
    path('create',create_pekerjaan,name='create_pekerjaan'),
    path('bekerja',list_bekerja,name="read_bekerja"),
    path('bekerja/create',create_bekerja,name="create_bekerja"),
    path('<str:nama>/update',update_pekerjaan,name="update_pekerjaan"),
    path('<str:nama>/delete',delete_pekerjaan,name='delete_pekerjaan'),
    
]

thecims/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('level/', include('level.urls')),
    path('warna-kulit/', include('warna_kulit.urls')),
    path('koleksi/', include('koleksi.urls')),
    path('tokoh/',include('tokoh.urls')),
    path('use_barang/',include('use_barang.urls')),
    path('pekerjaan/',include('pekerjaan.urls')),
    path('misi-utama/', include('misi_utama.urls')),
    path('menjalankan-misi-utama/', include('menjalankan_misi_utama.urls')),
    path('makanan/', include('makanan.urls')),
    path('makan/', include('makan.urls')),
    path('menggunakan-apparel/', include('menggunakan_apparel.urls')),
    path('registrasi/', include('registrasi.urls')),
]

pekerjaan/models.py
from django.db import models

# Create your models here.

pekerjaan/forms.py
from django import forms

class BekerjaForm(forms.Form):
    nama_tokoh = forms.CharField(label='nama_tokoh', max_length=50)
    nama_pekerjaan = forms.CharField(label='nama_pekerjaan', max_length=20)
    base_salary = forms.IntegerField(label="base_salary")

class PekerjaanForm(forms.Form):
    nama = forms.CharField(label='nama',max_length=20)
    base_honor = forms.IntegerField(label='base_honor')
  

pekerjaan/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.db import connection
from collections import namedtuple
from django.db import connection
from .forms import *
from datetime import datetime
# Create your views here.

def fetch_to_str(cursor):
    desc = cursor.fetchall()
    nt_result = tuple([col[0] for col in desc])
    return nt_result

def index(request):
    cursor = connection.cursor()
    
    result = []
    try:
        if request.session.has_key('username'):
            cursor.execute("SET SEARCH_PATH TO THECIMS")
            role = request.session['username'][2]
            cursor.execute("SELECT * FROM PEKERJAAN")
            result = cursor.fetchall()
            
            cursor.execute('''
                SELECT nama FROM PEKERJAAN
                WHERE nama NOT IN (SELECT pekerjaan FROM TOKOH WHERE pekerjaan IS NOT NULL)
                AND nama NOT IN (SELECT nama_pekerjaan FROM BEKERJA WHERE nama_pekerjaan IS NOT NULL)
                AND nama NOT IN (SELECT nama_pekerjaan FROM APPAREL WHERE nama_pekerjaan IS NOT NULL);
            ''')
            list_nama = fetch_to_str(cursor)
            print(type(result))
            print(list_nama)
            new_result = []
            for res in result:
                new_res = list(res)
                if res[0] in list_nama:
                    new_res.append(True)
                else:
                    new_res.append(False)
                new_result.append(new_res)
            print(new_result)
            return render(request, 'read_pekerjaan.html',{'result' : new_result})
        else:
            return HttpResponseRedirect("/login")
    except Exception as e:
        print(e)
    finally:
        cursor.close()

def create_pekerjaan(request):
    cursor = connection.cursor()
    try:
        if request.session.has_key('username') and request.session['username'][2] == 'Admin':
            if request.method == "POST":
                form = PekerjaanForm(request.POST)
                print(request.POST)
                print(form.errors)
                if form.is_valid():
                    cursor.execute("SET search_path to THECIMS");
                    cursor.execute(f'''
                        INSERT INTO PEKERJAAN VALUES
                        ('{form.cleaned_data['nama']}', {form.cleaned_data['base_honor']})
                    ''')
                    return HttpResponseRedirect('/pekerjaan')
            return render(request,"create_pekerjaan.html",{})
        else:
            return HttpResponseRedirect('/pekerjaan')
    except Exception as e:
        print(e)
    finally:
        cursor.close()

def update_pekerjaan(request,nama):
    cursor = connection.cursor()
    try:
        if request.session.has_key('username') and request.session['username'][2] == 'Admin':
            if request.method == "POST" :
                form = PekerjaanForm(request.POST)
                print(request.POST)
                print(form.errors)
                if form.is_valid():
                    cursor.execute("SET search_path to THECIMS");
                    cursor.execute(f'''
                        UPDATE PEKERJAAN 
                        SET base_honor = {form.cleaned_data['base_honor']}
                        WHERE nama = '{form.cleaned_data['nama']}';
                    ''')
                    return HttpResponseRedirect('/pekerjaan')
            else:
                return render(request,"update_pekerjaan.html",{'nama' :nama})
        else:
            return HttpResponseRedirect('/pekerjaan')
    except Exception as e:
        print(e)
    finally:
        cursor.close()


def delete_pekerjaan(request,nama):
    cursor = connection.cursor()
    try:
        if request.session.has_key('username'):
            print("halo")
            print(request.session['username'])
            if request.method == "POST" and request.session['username'][2] == 'Admin':
                print("masuk post admin")
                cursor.execute("SET search_path to THECIMS");
                cursor.execute(f'''
                        DELETE FROM PEKERJAAN 
                        WHERE nama = '{nama}'
                    ''')
                return HttpResponseRedirect('/pekerjaan')
    except Exception as e:
        print(e)
    finally:
        cursor.close()
def list_bekerja(request):
    cursor = connection.cursor()
    result = []
    try:
        if request.session.has_key('username'):
            role = request.session['username'][2]
            nama = request.session['username'][0]
            cursor.execute("SET SEARCH_PATH TO THECIMS")
            if role == "Pemain":
                cursor.execute(f'''
                SELECT nama_tokoh,nama_pekerjaan,timestamp,keberangkatan_ke,honor 
                FROM BEKERJA WHERE username_pengguna = '{nama}'
                ''')
            else:
                cursor.execute("SELECT username_pengguna,nama_tokoh,nama_pekerjaan,timestamp,keberangkatan_ke,honor FROM BEKERJA")
            result = cursor.fetchall()
            return render(request, 'read_bekerja.html',{'result' : result})
    except Exception as e:
        print(e)
    finally:
        cursor.close()

def create_bekerja(request):
    cursor = connection.cursor()
    result = []
    try:
        if request.session.has_key('username'):
            if request.method == "POST":
                form = BekerjaForm(request.POST)
                username_pengguna = request.session['username'][0]
                print("HMM")
                print(form.errors)
                if form.is_valid():
                    print("YES")
                    cursor.execute("SET SEARCH_PATH TO THECIMS")
                    cursor.execute(f'''
                        INSERT INTO BEKERJA VALUES
                        (
                            '{username_pengguna}',
                            '{form.cleaned_data['nama_tokoh']}',
                            '{datetime.now()}',
                            '{form.cleaned_data['nama_pekerjaan']}',
                            update_keberangkatan('{username_pengguna}','{form.cleaned_data['nama_tokoh']}' )
                            );
                    ''')
                    return HttpResponseRedirect("/pekerjaan/bekerja")
            else:
                cursor.execute("SET SEARCH_PATH TO THECIMS")
                cursor.execute(f'''
                    SELECT  DISTINCT nama_tokoh,nama_pekerjaan,p.base_honor
                    FROM BEKERJA b,PEKERJAAN p
                    WHERE b.nama_pekerjaan = p.nama
                    AND b.username_pengguna = '{request.session["username"][0]}'
                ''')
                result = cursor.fetchall()
                return render(request, 'create_bekerja.html',{'result' : result})
    except Exception as e:
        print(e)
    finally:
        cursor.close()

pekerjaan/templates/create_bekerja.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>List Bekerja</h1>
    <table>
        <tr>
            <th>No</th>
            <th>Nama Tokoh</th>
            <th>Nama Pekerjaan</th>
            <th>Base Salary</th>
            <th>Action</th>
        </tr>
        {% for res in result %}
            <tr>
                <td>{{forloop.counter}}</td>
                <form action="" method="post">
                    {% csrf_token %}
                    <td><input type="hidden"value="{{res.0}}" id="nama_tokoh" name="nama_tokoh" readonly >{{res.0}}</td>
                    <td><input type="hidden"value="{{res.1}}" id="nama_pekerjaan" name="nama_pekerjaan" readonly>{{res.1}}</td>
                    <td><input type="hidden"value="{{res.2}}" id="base_salary" name="base_salary" readonly>{{res.2}}</td>
                    <td><input type="submit" value="Mulai Bekerja"></td>
                </form>

            </tr>
        {% endfor %}
    </table>
{% endblock content %}

pekerjaan/templates/create_pekerjaan.html
{% extends 'base.html' %}
{% block content %}
    <h1>Form Buat Pekerjaan</h1>
    <form action="" method="post">
        {% csrf_token %}
        <label for="nama">Nama Pekerjaan:</label><br>
        <input type="text" id="nama" name="nama"><br>
        <label for="base_honor"> Base Honor:</label><br>
        <input type="text" id="base_honor" name="base_honor"><br> 
        <input type="submit" value="Simpan">
    </form>
{% endblock %}

pekerjaan/templates/read_bekerja.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>List Bekerja</h1>
    <table>
        <tr>
            <th>No</th>
            {% if request.session.username.2 == 'Admin' %}
                <th>Username Pemain</th>
            {% endif %}
            <th>Nama Tokoh</th>
            <th>Nama Pekerjaan</th>
            <th>Timestamp</th>
            <th>Keberangkatan ke</th>
            <th>Honor</th>
        </tr>
        {% for res in result %}
            <tr>
                <td>{{forloop.counter}}</td>
                {% if request.session.username.2 == 'Admin' %}
                    <td>{{res.0}}</td>
                    <td>{{res.1}}</td>
                    <td>{{res.2}}</td>
                    <td>{{res.3}}</td>
                    <td>{{res.4}}</td>
                    <td>{{res.5}}</td>
                {% else %}
                    <td>{{res.0}}</td>
                    <td>{{res.1}}</td>
                    <td>{{res.2}}</td>
                    <td>{{res.3}}</td>
                    <td>{{res.4}}</td>
                {% endif %}

            </tr>
        {% endfor %}
    </table>
{% endblock content %}

pekerjaan/templates/read_pekerjaan.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
 <link rel="stylesheet" href="{% static 'read_pekerjaan.css' %}">
{% endblock meta %}
{% block content %}
    <h1>List Pekerjaan</h1>
    <table>
        <tr>
            <th>Nama Pekerjaan</th>
            <th>Base Salary</th>
            {% if request.session.username.2 == 'Admin' %}
                <th>Action</th>
            {% endif %}
        </tr>
        {% for res in result %}
            <tr>
                <td>{{ res.0 }}</td>
                <td>{{res.1}}</td>
                <td>
                    {% if request.session.username.2 == 'Admin' %}
                    <a href="{% url 'pekerjaan:update_pekerjaan' res.0 %}">UPDATE</a>
                    {% if res.2 == True %}
                    <form action="{% url 'pekerjaan:delete_pekerjaan' res.0 %}" method="post" class="inline">
                        {% csrf_token %}
                        <button type="submit" class="link-button">DELETE</button>
                    </form>
                    
                    {% endif %}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}

pekerjaan/templates/update_pekerjaan.html
{% extends 'base.html' %}
{% block content %}
    <h1>Form Update Pekerjaan</h1>
    <form action="" method="post">
        {% csrf_token %}
        <label for="nama">Nama Pekerjaan:</label><br>
        <input type="text" id="nama" name="nama" placeholder="{{nama}}" value="{{nama}}" readonly><br>
        <label for="base_honor"> Base Honor:</label><br>
        <input type="text" id="base_honor" name="base_honor"><br> 
        <input type="submit" value="Simpan">
    </form>
{% endblock %}