home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('homepage', views.loggedInView, name='login'),
    path('logout', views.logout, name='login'),
]

menggunakan_apparel/urls.py
from django.urls import path
from .views import *

app_name = 'menggunakan_apparel'
urlpatterns = [
    path('', read_menggunakan_apparel, name='read_menggunakan_apparel'),
    path('create', create_menggunakan_apparel_1, name='create_menggunakan_apparel_1'),
    path('<nama_tokoh>/create', create_menggunakan_apparel_2, name = 'create_menggunakan_apparel_2'),
    path('<username>/<nama>/<id>/delete', delete_menggunakan_apparel, name='delete_menggunakan_apparel')
]

thecims/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('level/', include('level.urls')),
    path('warna-kulit/', include('warna_kulit.urls')),
    path('koleksi/', include('koleksi.urls')),
    path('tokoh/',include('tokoh.urls')),
    path('use_barang/',include('use_barang.urls')),
    path('pekerjaan/',include('pekerjaan.urls')),
    path('misi-utama/', include('misi_utama.urls')),
    path('menjalankan-misi-utama/', include('menjalankan_misi_utama.urls')),
    path('makanan/', include('makanan.urls')),
    path('makan/', include('makan.urls')),
    path('menggunakan-apparel/', include('menggunakan_apparel.urls')),
    path('registrasi/', include('registrasi.urls')),
]

menggunakan_apparel/models.py
from django.db import models

# Create your models here.

menggunakan_apparel/views.py
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render
from django.db import connection
from django.shortcuts import redirect

# role: Admin & Pemain
def read_menggunakan_apparel(request):
    response = {}
    if request.session.has_key('username'):
        with connection.cursor() as cursor:
            cursor.execute("SET SEARCH_PATH TO THECIMS")
            if request.session['username'][2] == "Admin":
                cursor.execute("SELECT MA.username_pengguna, MA.nama_tokoh, KJB.nama, A.warna_apparel, A.nama_pekerjaan, A.kategori_apparel, MA.id_koleksi FROM MENGGUNAKAN_APPAREL MA, KOLEKSI_JUAL_BELI KJB, APPAREL A WHERE MA.id_koleksi = KJB.id_koleksi AND KJB.id_koleksi = A.id_koleksi")
            else:
                cursor.execute("SELECT MA.username_pengguna, MA.nama_tokoh, KJB.nama, A.warna_apparel, A.nama_pekerjaan, A.kategori_apparel, MA.id_koleksi FROM MENGGUNAKAN_APPAREL MA, KOLEKSI_JUAL_BELI KJB, APPAREL A WHERE MA.id_koleksi = KJB.id_koleksi AND KJB.id_koleksi = A.id_koleksi AND MA.username_pengguna = %s", [request.session['username'][0]])
            response['daftar_menggunakan_apparel'] = cursor.fetchall()          
            response['role'] = request.session['username'][2]
        return render(request, 'read_menggunakan_apparel.html', response)
    return redirect('/login')

def create_menggunakan_apparel_1(request):
    if request.session.has_key('username'):
        if request.session['username'][2] == "Pemain":
            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO THECIMS")
                cursor.execute("SELECT nama FROM TOKOH WHERE username_pengguna = %s", [request.session['username'][0]])
                nama_tokoh = cursor.fetchall()
                result_list_nama = []
                for i in nama_tokoh:
                    result = ''.join(i)
                    result_list_nama.append(result)
                if request.method == "POST":
                    dropdown_nama_tokoh = request.POST['nama_tokoh']
                    return redirect(dropdown_nama_tokoh + '/create')
            return render(request, 'create_menggunakan_apparel_1.html', {'result_list_nama': result_list_nama})
    return redirect('/login')

# role: Pemain
def create_menggunakan_apparel_2(request, nama_tokoh):
    if request.session.has_key('username'):
        if request.session['username'][2] == "Pemain":
            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO THECIMS")
                cursor.execute("SELECT KT.id_koleksi FROM KOLEKSI_TOKOH KT WHERE KT.username_pengguna = %s AND KT.nama_tokoh = %s AND KT.id_koleksi IN (SELECT A.id_koleksi FROM APPAREL A)", [request.session['username'][0], nama_tokoh])
                apparel = cursor.fetchall()
                result_list_apparel = []
                for i in apparel:
                    result = ''.join(i)
                    result_list_apparel.append(result)
                if request.method == "POST":
                    dropdown_apparel = request.POST['apparel']
                    if check_menggunakan_apparel_availibility(request.session['username'][0], nama_tokoh, dropdown_apparel):
                        cursor.execute("INSERT INTO MENGGUNAKAN_APPAREL VALUES(%s, %s, %s)", [request.session['username'][0], nama_tokoh, dropdown_apparel])
                        return redirect('/menggunakan-apparel')
                    else:
                        return render(request, 'create_menggunakan_apparel_2.html', {'nama_tokoh': nama_tokoh, 'result_list_apparel': result_list_apparel, 'error_message': "Tokoh sedang memakai apparel tersebut. Silakan pilih apparel lain."})
            return render(request, 'create_menggunakan_apparel_2.html', {'nama_tokoh': nama_tokoh, 'result_list_apparel': result_list_apparel, 'error_message': None})
    return redirect('/login')

# role: Pemain
def delete_menggunakan_apparel(request, username, nama, id):
    with connection.cursor() as cursor:
        cursor.execute("SET SEARCH_PATH TO THECIMS")
        cursor.execute("DELETE FROM MENGGUNAKAN_APPAREL WHERE username_pengguna = %s AND nama_tokoh = %s AND id_koleksi = %s", [username, nama, id])
    return redirect('/menggunakan-apparel')

def check_menggunakan_apparel_availibility(username, name, apparel):
    result = True
    with connection.cursor() as cursor:
        cursor.execute("SET SEARCH_PATH TO THECIMS")
        cursor.execute("SELECT * FROM MENGGUNAKAN_APPAREL WHERE username_pengguna = %s AND nama_tokoh = %s AND id_koleksi = %s", [username, name, apparel])
        level_row = cursor.fetchone()
        if level_row != None:
            result = False
    return result

menggunakan_apparel/templates/create_menggunakan_apparel_1.html
{% include "navbar_pemain.html" %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Create Menggunakan Apparel</title>
  </head>
  <body>
      <form method="POST">
        {% csrf_token %}
        <h1>Form Buat Menggunakan Apparel</h1>
        <br>
        Nama Tokoh
        <div>
            <select name = 'nama_tokoh' id = 'nama_tokoh' required>
                {% for nama in result_list_nama %}
                <option value = {{nama}}> {{ nama }} </option>
                {% endfor %}
            </select>
        </div>
        <br>
        <button type="submit" value="Submit">Selanjutnya</button>
      </form>
  </body>
</html>

menggunakan_apparel/templates/create_menggunakan_apparel_2.html
{% include "navbar_pemain.html" %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Create Menggunakan Apparel</title>
  </head>
  <body>
      <form action="{% url 'menggunakan_apparel:create_menggunakan_apparel_2' nama_tokoh=nama_tokoh %}" method="POST">
        {% csrf_token %}
        <h1>Form Buat Menggunakan Apparel</h1>
        <br>
        Apparel untuk {{ nama_tokoh }}
        <div>
            <select name = 'apparel' id = 'apparel' required>
                {% for apparel in result_list_apparel %}
                <option value = {{apparel}}> {{ apparel }} </option>
                {% endfor %}
            </select>
        </div>
        <br>
        <button type="submit" value="Submit">Pakai</button>
      </form>
      <form action="/menggunakan-apparel/create">
        <input type="submit" value="Kembali" />
    </form>
    {% if error_message != null %}
    <h6>{{ error_message }}</h6>
    {% endif %}
  </body>
</html>

menggunakan_apparel/templates/read_menggunakan_apparel.html
{% if role == "Admin" %}
{% include "navbar_admin.html" %}
{% endif %}
{% if role == "Pemain" %}
{% include "navbar_pemain.html" %}
{% endif %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>List Menggunakan Apparel</title>
    <style>
        table, th, td {
          border: 1px solid black;
          border-collapse: collapse;
        }
    </style>
  </head>
  <body>
      <h1>List Menggunakan Apparel</h1>
      <br>
      <table>
          <thead>
              <tr>
                  <th>No.</th>
                  {% if role == "Admin" %}
                  <th>Username Pemain</th>
                  {% endif %}
                  <th>Nama Tokoh</th>
                  <th>Nama Apparel</th>
                  <th>Warna</th>
                  <th>Nama Pekerjaan</th>
                  <th>Kategori</th>
                  {% if role == "Pemain" %}
                  <th>Action</th>
                  {% endif %}
              </tr>
          </thead>
          <tbody>
              {% for ma in daftar_menggunakan_apparel %}
              <tr>
                  <td>{{ forloop.counter }}</td>
                  {% if role == "Admin" %}
                  <td>{{ ma.0 }}</td>
                  {% endif %}
                  <td>{{ ma.1 }}</td>
                  <td>{{ ma.2 }}</td>
                  <td>{{ ma.3 }}</td>
                  <td>{{ ma.4 }}</td>
                  <td>{{ ma.5 }}</td>
                  {% if role == "Pemain" %}
                  <td><a href="{{ ma.0 }}/{{ ma.1 }}/{{ ma.6 }}/delete">Lepas</td>
                  {% endif %}
              </tr>
              {% endfor %}
          </tbody>
      </table>
  </body>
</html>